### ISSUE TITLE
A system that automatically takes you to another plot

### ISSUE THREAD

**Issue by MrBlasyMSK** [supercrafter333/PlotRate#1]
I wanted to know if it is possible to make that instead of the player having to look for a plot in which someone is walking, to put a command like / pr a (plotrate auto) and take him to a random plot (that has an owner) to so that the user can score for that plot

**Comment by supercrafter333** [comment]
Yes, that's possible. Great Idea! I'll add it in the next version :)

**Comment by supercrafter333** [comment]
Done in V1.1.0. Thanks for your gr8 Idea!
